
let createBasicMaterial = MainEditorBasicMaterialAdaptor.create;

let getBasicMaterialColor = MainEditorBasicMaterialAdaptor.getBasicMaterialColor;

let setBasicMaterialColor = MainEditorBasicMaterialAdaptor.setBasicMaterialColor;