let unsafeGetCurrentGameObject = CurrentGameObjectCommonService.unsafeGetCurrentGameObject;

let getCurrentGameObject = CurrentGameObjectCommonService.getCurrentGameObject;

let hasCurrentGameObject = CurrentGameObjectCommonService.hasCurrentGameObject;

let setCurrentGameObject = CurrentGameObjectCommonService.setCurrentGameObject;

let clearCurrentGameObject = CurrentGameObjectCommonService.clearCurrentGameObject;
