// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var Hehe_test = 0;

var Sinon_test = 0;

var Test1_test = 0;

var Test2_test = 0;

var Sinon = 0;

var Index = 0;

var AppStore = 0;

var IndexStore = 0;

var StringStore = 0;

var Ant = 0;

var UiTool = 0;

var Reductive = 0;

var Middleware = 0;

var ReduxThunk = 0;

var App = 0;

var DebugUtils = 0;

exports.Hehe_test   = Hehe_test;
exports.Sinon_test  = Sinon_test;
exports.Test1_test  = Test1_test;
exports.Test2_test  = Test2_test;
exports.Sinon       = Sinon;
exports.Index       = Index;
exports.AppStore    = AppStore;
exports.IndexStore  = IndexStore;
exports.StringStore = StringStore;
exports.Ant         = Ant;
exports.UiTool      = UiTool;
exports.Reductive   = Reductive;
exports.Middleware  = Middleware;
exports.ReduxThunk  = ReduxThunk;
exports.App         = App;
exports.DebugUtils  = DebugUtils;
/* No side effect */
