// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';


var Sinon = 0;

var Test1_test = 0;

var Test2_test = 0;

var Index = 0;

var App = 0;

var AppStore = 0;

var SimpleStore = 0;

var Reductive = 0;

var Middleware = 0;

var ReduxThunk = 0;

exports.Sinon       = Sinon;
exports.Test1_test  = Test1_test;
exports.Test2_test  = Test2_test;
exports.Index       = Index;
exports.App         = App;
exports.AppStore    = AppStore;
exports.SimpleStore = SimpleStore;
exports.Reductive   = Reductive;
exports.Middleware  = Middleware;
exports.ReduxThunk  = ReduxThunk;
/* No side effect */
