// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var Sinon_test = 0;

var Test1_test = 0;

var App_test = 0;

var NumberInput_test = 0;

var Tester = 0;

var ReactTestRenderer_test = 0;

var ReactShallowRenderer_test = 0;

var Sinon = 0;

var ReactTestRenderer = 0;

var ReactShallowRenderer = 0;

var Index = 0;

var MainEditor = 0;

var MainEditorStore = 0;

var AppConfig = 0;

var DomAtom = 0;

var MainEditorAtom = 0;

var NumberInputAtom = 0;

var AppStore = 0;

var IndexStore = 0;

var StringStore = 0;

var Ant = 0;

var UiTool = 0;

var Reductive = 0;

var Middleware = 0;

var ReduxThunk = 0;

var NumberInput = 0;

var App = 0;

var DebugUtils = 0;

exports.Sinon_test                = Sinon_test;
exports.Test1_test                = Test1_test;
exports.App_test                  = App_test;
exports.NumberInput_test          = NumberInput_test;
exports.Tester                    = Tester;
exports.ReactTestRenderer_test    = ReactTestRenderer_test;
exports.ReactShallowRenderer_test = ReactShallowRenderer_test;
exports.Sinon                     = Sinon;
exports.ReactTestRenderer         = ReactTestRenderer;
exports.ReactShallowRenderer      = ReactShallowRenderer;
exports.Index                     = Index;
exports.MainEditor                = MainEditor;
exports.MainEditorStore           = MainEditorStore;
exports.AppConfig                 = AppConfig;
exports.DomAtom                   = DomAtom;
exports.MainEditorAtom            = MainEditorAtom;
exports.NumberInputAtom           = NumberInputAtom;
exports.AppStore                  = AppStore;
exports.IndexStore                = IndexStore;
exports.StringStore               = StringStore;
exports.Ant                       = Ant;
exports.UiTool                    = UiTool;
exports.Reductive                 = Reductive;
exports.Middleware                = Middleware;
exports.ReduxThunk                = ReduxThunk;
exports.NumberInput               = NumberInput;
exports.App                       = App;
exports.DebugUtils                = DebugUtils;
/* No side effect */
