let getDragedSceneGraphData = MainEditorSceneTreeBuss.getDragedSceneGraphData;

let setParent = MainEditorSceneTreeBuss.setParent;

let setParentKeepOrder = MainEditorSceneTreeBuss.setTransformParentKeepOrder;

let isGameObjectRelationError = MainEditorSceneTreeBuss.isGameObjectRelationError;

let getSceneGraphDataFromEngine = MainEditorSceneTreeBuss.getSceneGraphDataFromEngine;