let getCurrentGameObjectBasicMaterialColor = MainEditorMaterialBuss.getCurrentGameObjectBasicMaterialColor;

let setCurrentGameObjectBasicMaterialColor = MainEditorMaterialBuss.setCurrentGameObjectBasicMaterialColor;