let createBasicMaterial = BasicMaterialCommonService.createBasicMaterial;

let getBasicMaterialColor = BasicMaterialCommonService.getBasicMaterialColor;

let setBasicMaterialColor = BasicMaterialCommonService.setBasicMaterialColor;